use aes_gcm::aead::{Aead, KeyInit};
use aes_gcm::{Aes128Gcm, Nonce};
use base64::Engine as _;

// Compile-time flag generated by build.rs
include!(concat!(env!("OUT_DIR"), "/vrm_embedded.rs"));

// Encrypted VRM bytes embedded at compile time
static DEFAULT_VRM_BYTES: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/default_vrm.enc"));

// Same key used in build.rs — must stay in sync
const DEFAULT_VRM_KEY: [u8; 16] = [
    0x4d, 0x50, 0x41, 0x49, // MPAI
    0x56, 0x52, 0x4d, 0x4b, // VRMK
    0x32, 0x30, 0x32, 0x36, // 2026
    0xde, 0xad, 0xbe, 0xef,
];

fn decrypt_vrm_bytes() -> Result<Vec<u8>, String> {
    if !HAS_DEFAULT_VRM || DEFAULT_VRM_BYTES.is_empty() {
        return Err("No default VRM embedded in this build".into());
    }

    if DEFAULT_VRM_BYTES.len() < 12 {
        return Err("Encrypted VRM data is too short".into());
    }

    let nonce_bytes = &DEFAULT_VRM_BYTES[..12];
    let ciphertext = &DEFAULT_VRM_BYTES[12..];

    let cipher = Aes128Gcm::new_from_slice(&DEFAULT_VRM_KEY)
        .map_err(|e| format!("AES key error: {e}"))?;
    let nonce = Nonce::from_slice(nonce_bytes);

    cipher
        .decrypt(nonce, ciphertext)
        .map_err(|e| format!("AES-GCM decryption failed: {e}"))
}

/// Returns the default VRM as a base64-encoded string.
#[tauri::command]
pub fn load_default_vrm() -> Result<String, String> {
    let plain = decrypt_vrm_bytes()?;
    Ok(base64::engine::general_purpose::STANDARD.encode(&plain))
}

/// Returns whether a default VRM is embedded in this build.
#[tauri::command]
pub fn is_default_vrm_available() -> bool {
    HAS_DEFAULT_VRM
}
