/// AES-128 key for default VRM decryption.
/// Generated by build.rs — contains the actual key when vrm_key.bin exists,
/// or a zero placeholder when building without VRM (CI/opensource).
include!(concat!(env!("OUT_DIR"), "/vrm_key_const.rs"));
